cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    # path('payment/', include('payment.urls', namespace='payment')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    # path('welcome', views.welcome, name='welcome'),
    # path('deli/', include(('deli.urls', 'shop'), namespace='deli')),
    # path('about/', include(('about.urls', 'shop'), namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# from django.contrib.auth.models import User

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # author = models.ForeignKey(User, on_delete=models.CASCADE,
    #                            related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    id = models.AutoField(primary_key=True, help_text='Код книги')
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Post, Comment
from cart.forms import CartAddProductForm
from .forms import CommentForm


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)
    # Список активных комментариев для этой статьи.
    comments = post.comments.filter(active=True)
    # comment_form = CommentForm()
    new_comment = None
    if request.method == 'POST':
        # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = post
            # Сохраняем комментарий в базе данных.
            new_comment.save()
        else:
            comment_form = CommentForm()
    return render(request, 'shop/product/detail.html', {'post': post,
                                                        'comments': comments,
                                                        'new_comment': new_comment,
                                                        'comment_form': comment_form})


def product_list(request, category_slug=None):
    category = Category.name
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product})

    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

# def deli(request):
#     return render(request, 'shop/deli.html')

# def about(request):
#     return render(request, 'shop/about.html')

shop/templates/shop/about.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Книжный магазин "Книжная полка"{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header" align="center">
    <img src="media\products\2021\05\03\7.png" height="100" width="120" align="center">
    <a href="/" class="logo">Главная</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" href="">Доставка и оплата</a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" href="">О нас</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" class="cart" style="color:white">
        <!--       id="subheader"-->
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        В корзине:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_items }} item{{ total_items|pluralize }},
            ${{ cart.get_total_price }}
        </a>
        {% else %}
        Корзина&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        {% endif %}
        {% endwith %}
    </a>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<table>
    <tr class="footer">
        <td> Адрес: Барнаул, ул. Ленина, 76</td>
        <td> Тел.: 8-800-555-35-35</td>
    </tr>
</table>
</body>
</html>

shop/templates/shop/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Книжный магазин "Книжная полка"{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header" align="center">
    <a href="/">
<!--        <img src="media\products\2021\05\03\7.png" height="100" width="120" align="center">-->
        <img src="{% static 'img/7.png' %}" height="100" width="120" align="center">
    </a>
    <a href="/" class="logo">Главная</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" href="">Доставка и оплата</a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" href="">О нас</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" class="cart" style="color:white" href="{% url 'cart:cart_detail' %}">
        <!--       id="subheader"-->

        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        В корзине:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_items }} item{{ total_items|pluralize }},
            ${{ cart.get_total_price }}
        </a>
        {% else %}
        Корзина&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        {% endif %}
        {% endwith %}
    </a>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<table>
    <tr class="footer">
        <td> Адрес: Барнаул, ул. Ленина, 76</td>
        <td> Тел.: 8-800-555-35-35</td>
    </tr>
</table>
</body>
</html>

shop/templates/shop/deli.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Книжный магазин "Книжная полка"{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header" align="center">
    <img src="media\products\2021\05\03\7.png" height="100" width="120" align="center">
    <a href="/" class="logo">Главная</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" href="">Доставка и оплата</a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" href="">О нас</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="logo" class="cart" style="color:white">
        <!--       id="subheader"-->
        {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        В корзине:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_items }} item{{ total_items|pluralize }},
            ${{ cart.get_total_price }}
        </a>
        {% else %}
        Корзина&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        {% endif %}
        {% endwith %}
    </a>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<table>
    <tr class="footer">
        <td> Адрес: Барнаул, ул. Ленина, 76</td>
        <td> Тел.: 8-800-555-35-35</td>
    </tr>
</table>
</body>
</html>